# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hbase_pb2 as hbase__pb2


class HBaseServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/hbase.HBaseService/Get',
        request_serializer=hbase__pb2.GetRequest.SerializeToString,
        response_deserializer=hbase__pb2.Result.FromString,
        )
    self.Scan = channel.unary_stream(
        '/hbase.HBaseService/Scan',
        request_serializer=hbase__pb2.ScanRequest.SerializeToString,
        response_deserializer=hbase__pb2.Result.FromString,
        )
    self.Delete = channel.unary_unary(
        '/hbase.HBaseService/Delete',
        request_serializer=hbase__pb2.DeleteRequest.SerializeToString,
        response_deserializer=hbase__pb2.OK.FromString,
        )
    self.Put = channel.unary_unary(
        '/hbase.HBaseService/Put',
        request_serializer=hbase__pb2.PutRequest.SerializeToString,
        response_deserializer=hbase__pb2.OK.FromString,
        )


class HBaseServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Scan(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HBaseServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=hbase__pb2.GetRequest.FromString,
          response_serializer=hbase__pb2.Result.SerializeToString,
      ),
      'Scan': grpc.unary_stream_rpc_method_handler(
          servicer.Scan,
          request_deserializer=hbase__pb2.ScanRequest.FromString,
          response_serializer=hbase__pb2.Result.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=hbase__pb2.DeleteRequest.FromString,
          response_serializer=hbase__pb2.OK.SerializeToString,
      ),
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=hbase__pb2.PutRequest.FromString,
          response_serializer=hbase__pb2.OK.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hbase.HBaseService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
