# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc import Channel

import hbase_pb2 as hbase__pb2

from typing import Iterator


class HBaseServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel: Channel) -> None: ...

  def Get(self, request: hbase__pb2.GetRequest) -> hbase__pb2.Result: ...

  def Scan(self, request: hbase__pb2.ScanRequest) -> Iterator[hbase__pb2.Result]: ...

  def Delete(self, request: hbase__pb2.DeleteRequest) -> hbase__pb2.OK: ...

  def put(self, request: hbase__pb2.PutRequest) -> hbase__pb2.OK: ...
