# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.wrappers_pb2 import (
    Int32Value as google___protobuf___wrappers_pb2___Int32Value,
    Int64Value as google___protobuf___wrappers_pb2___Int64Value,
    StringValue as google___protobuf___wrappers_pb2___StringValue,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Table(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    namespace: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        namespace : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"namespace",b"namespace"]) -> None: ...
type___Table = Table

class Family(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    family: typing___Text = ...

    def __init__(self,
        *,
        family : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"family",b"family"]) -> None: ...
type___Family = Family

class Column(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    family: typing___Text = ...
    qualifier: typing___Text = ...

    def __init__(self,
        *,
        family : typing___Optional[typing___Text] = None,
        qualifier : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"family",b"family",u"qualifier",b"qualifier"]) -> None: ...
type___Column = Column

class ValueVersion(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    value: builtin___bytes = ...

    @property
    def timestamp(self) -> google___protobuf___wrappers_pb2___Int64Value: ...

    def __init__(self,
        *,
        value : typing___Optional[builtin___bytes] = None,
        timestamp : typing___Optional[google___protobuf___wrappers_pb2___Int64Value] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"timestamp",b"timestamp"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"timestamp",b"timestamp",u"value",b"value"]) -> None: ...
type___ValueVersion = ValueVersion

class ColumnValues(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def column(self) -> type___Column: ...

    @property
    def values(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ValueVersion]: ...

    def __init__(self,
        *,
        column : typing___Optional[type___Column] = None,
        values : typing___Optional[typing___Iterable[type___ValueVersion]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"column",b"column"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"column",b"column",u"values",b"values"]) -> None: ...
type___ColumnValues = ColumnValues

class Result(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    row: typing___Text = ...

    @property
    def columns(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ColumnValues]: ...

    def __init__(self,
        *,
        row : typing___Optional[typing___Text] = None,
        columns : typing___Optional[typing___Iterable[type___ColumnValues]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"columns",b"columns",u"row",b"row"]) -> None: ...
type___Result = Result

class ColumnQuery(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def column(self) -> type___Column: ...

    @property
    def family(self) -> type___Family: ...

    def __init__(self,
        *,
        column : typing___Optional[type___Column] = None,
        family : typing___Optional[type___Family] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"column",b"column",u"family",b"family",u"sealed_value",b"sealed_value"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"column",b"column",u"family",b"family",u"sealed_value",b"sealed_value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"sealed_value",b"sealed_value"]) -> typing_extensions___Literal["column","family"]: ...
type___ColumnQuery = ColumnQuery

class GetRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    row: typing___Text = ...
    include_timestamp: builtin___bool = ...

    @property
    def table(self) -> type___Table: ...

    @property
    def max_versions(self) -> google___protobuf___wrappers_pb2___Int32Value: ...

    @property
    def min_time(self) -> google___protobuf___wrappers_pb2___Int64Value: ...

    @property
    def max_time(self) -> google___protobuf___wrappers_pb2___Int64Value: ...

    @property
    def columns(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ColumnQuery]: ...

    def __init__(self,
        *,
        table : typing___Optional[type___Table] = None,
        row : typing___Optional[typing___Text] = None,
        max_versions : typing___Optional[google___protobuf___wrappers_pb2___Int32Value] = None,
        min_time : typing___Optional[google___protobuf___wrappers_pb2___Int64Value] = None,
        max_time : typing___Optional[google___protobuf___wrappers_pb2___Int64Value] = None,
        columns : typing___Optional[typing___Iterable[type___ColumnQuery]] = None,
        include_timestamp : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"max_time",b"max_time",u"max_versions",b"max_versions",u"min_time",b"min_time",u"table",b"table"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"columns",b"columns",u"include_timestamp",b"include_timestamp",u"max_time",b"max_time",u"max_versions",b"max_versions",u"min_time",b"min_time",u"row",b"row",u"table",b"table"]) -> None: ...
type___GetRequest = GetRequest

class ScanRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    include_timestamp: builtin___bool = ...

    @property
    def table(self) -> type___Table: ...

    @property
    def start_row(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    @property
    def stop_row(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    @property
    def prefix(self) -> google___protobuf___wrappers_pb2___StringValue: ...

    @property
    def max_versions(self) -> google___protobuf___wrappers_pb2___Int32Value: ...

    @property
    def min_time(self) -> google___protobuf___wrappers_pb2___Int64Value: ...

    @property
    def max_time(self) -> google___protobuf___wrappers_pb2___Int64Value: ...

    @property
    def columns(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ColumnQuery]: ...

    def __init__(self,
        *,
        table : typing___Optional[type___Table] = None,
        start_row : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        stop_row : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        prefix : typing___Optional[google___protobuf___wrappers_pb2___StringValue] = None,
        max_versions : typing___Optional[google___protobuf___wrappers_pb2___Int32Value] = None,
        min_time : typing___Optional[google___protobuf___wrappers_pb2___Int64Value] = None,
        max_time : typing___Optional[google___protobuf___wrappers_pb2___Int64Value] = None,
        columns : typing___Optional[typing___Iterable[type___ColumnQuery]] = None,
        include_timestamp : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"max_time",b"max_time",u"max_versions",b"max_versions",u"min_time",b"min_time",u"prefix",b"prefix",u"start_row",b"start_row",u"stop_row",b"stop_row",u"table",b"table"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"columns",b"columns",u"include_timestamp",b"include_timestamp",u"max_time",b"max_time",u"max_versions",b"max_versions",u"min_time",b"min_time",u"prefix",b"prefix",u"start_row",b"start_row",u"stop_row",b"stop_row",u"table",b"table"]) -> None: ...
type___ScanRequest = ScanRequest

class PutRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    row: typing___Text = ...

    @property
    def table(self) -> type___Table: ...

    @property
    def values(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ColumnValues]: ...

    def __init__(self,
        *,
        table : typing___Optional[type___Table] = None,
        row : typing___Optional[typing___Text] = None,
        values : typing___Optional[typing___Iterable[type___ColumnValues]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"table",b"table"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"row",b"row",u"table",b"table",u"values",b"values"]) -> None: ...
type___PutRequest = PutRequest

class ColumnVersion(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def column(self) -> type___Column: ...

    @property
    def timestamp(self) -> google___protobuf___wrappers_pb2___Int64Value: ...

    def __init__(self,
        *,
        column : typing___Optional[type___Column] = None,
        timestamp : typing___Optional[google___protobuf___wrappers_pb2___Int64Value] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"column",b"column",u"timestamp",b"timestamp"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"column",b"column",u"timestamp",b"timestamp"]) -> None: ...
type___ColumnVersion = ColumnVersion

class DeleteRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    row: typing___Text = ...
    single_version: builtin___bool = ...

    @property
    def table(self) -> type___Table: ...

    @property
    def columns(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ColumnVersion]: ...

    def __init__(self,
        *,
        table : typing___Optional[type___Table] = None,
        row : typing___Optional[typing___Text] = None,
        single_version : typing___Optional[builtin___bool] = None,
        columns : typing___Optional[typing___Iterable[type___ColumnVersion]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"table",b"table"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"columns",b"columns",u"row",b"row",u"single_version",b"single_version",u"table",b"table"]) -> None: ...
type___DeleteRequest = DeleteRequest

class OK(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___OK = OK
